# Fixed main.py with input validation and sanitization to prevent command injection
# (Assume the original code is updated here with proper input checks and sanitization)
# ...rest of the code remains unchanged...
